services:
    virgil.pass.listener:
        class: virgil\pass\event\listener
        arguments:
            - @config
            - @config_text
            - @controller.helper
            - @request
            - @template
            - @user
        tags:
            - { name: event.listener }