services:
    virgil.login.listener:
        class: virgil\auth\event\listener
        arguments:
            - @config
            - @config_text
            - @controller.helper
            - @request
            - @template
            - @user
        tags:
            - { name: event.listener }